ALTER TABLE Students
    MODIFY COLUMN name VARCHAR(20) NOT NULL DEFAULT '',
    MODIFY COLUMN surname VARCHAR(20) NOT NULL DEFAULT '';

# еще вариант
ALTER TABLE Students
    ALTER COLUMN name SET DEFAULT '',
    ALTER COLUMN surname SET DEFAULT '';